[package]
name = "stu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tabled = "0.10.0"
serde_json = "1.0"
serde = {version = "1.0.152", features = ["derive"]}
sqlite = "0.30.3"
tempfile = "3.3.0"
